/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


import Controlador.ControladorJDAnadirCliente;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Alejandroo
 */
public class JDAnadirCliente extends javax.swing.JDialog {

    private ControladorJDAnadirCliente controlador;
    /**
     * Creates new form VistaAnadirCliente
     * @param parent
     * @param modal
     */
    public JDAnadirCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controlador = new ControladorJDAnadirCliente(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNombreCliente = new javax.swing.JTextField();
        jTextFieldApellidosCliente = new javax.swing.JTextField();
        jTextFieldDniCliente = new javax.swing.JTextField();
        jTextFieldDireccionCliente = new javax.swing.JTextField();
        jTextFieldEmailCliente = new javax.swing.JTextField();
        jTextFieldTelefonoCliente = new javax.swing.JTextField();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextFieldNombreCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        jTextFieldNombreCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNombreClienteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreClienteKeyTyped(evt);
            }
        });

        jTextFieldApellidosCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellidos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        jTextFieldApellidosCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldApellidosClienteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldApellidosClienteKeyTyped(evt);
            }
        });

        jTextFieldDniCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DNI", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        jTextFieldDniCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDniClienteActionPerformed(evt);
            }
        });
        jTextFieldDniCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDniClienteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDniClienteKeyTyped(evt);
            }
        });

        jTextFieldDireccionCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Direccion", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jTextFieldEmailCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jTextFieldTelefonoCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefono", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        jTextFieldTelefonoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefonoClienteActionPerformed(evt);
            }
        });
        jTextFieldTelefonoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldTelefonoClienteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTelefonoClienteKeyTyped(evt);
            }
        });

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonBorrar.setText("Borrar Todo");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Añadir Cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonAceptar)
                .addGap(64, 64, 64)
                .addComponent(jButtonBorrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jButtonCancelar)
                .addGap(34, 34, 34))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(jTextFieldApellidosCliente)
                    .addComponent(jTextFieldDniCliente)
                    .addComponent(jTextFieldDireccionCliente)
                    .addComponent(jTextFieldEmailCliente)
                    .addComponent(jTextFieldTelefonoCliente))
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldApellidosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
      this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        controlador.limpiaDatos();
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jTextFieldNombreClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreClienteKeyPressed
char c = evt.getKeyChar();
        if(Character.isDigit(c) || !Character.isLetter(c) && evt.getKeyCode() != KeyEvent.VK_BACK_SPACE && evt.getKeyCode() != KeyEvent.VK_CAPS_LOCK)  {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Debes introducir letras o numeros", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTextFieldNombreClienteKeyPressed

    private void jTextFieldNombreClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreClienteKeyTyped
  char c = evt.getKeyChar();
        if(Character.isDigit(c) || !Character.isLetter(c)) {
            evt.consume();
            
        }
    }//GEN-LAST:event_jTextFieldNombreClienteKeyTyped

    private void jTextFieldApellidosClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApellidosClienteKeyPressed
char c = evt.getKeyChar();
        if(Character.isDigit(c) || !Character.isLetter(c) && evt.getKeyCode() != KeyEvent.VK_BACK_SPACE && evt.getKeyCode() != KeyEvent.VK_CAPS_LOCK)  {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Debes introducir letras o numeros", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTextFieldApellidosClienteKeyPressed

    private void jTextFieldApellidosClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApellidosClienteKeyTyped
char c = evt.getKeyChar();
        if(Character.isDigit(c) || !Character.isLetter(c)) {
            evt.consume();
            
        }
    }//GEN-LAST:event_jTextFieldApellidosClienteKeyTyped

    private void jTextFieldDniClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDniClienteKeyTyped
char c = evt.getKeyChar();
       
        if(jTextFieldDniCliente.getText().length()== 9) {
           evt.consume();
           JOptionPane.showMessageDialog(this, "El DNI no puede contener mas de 9 caracteres", "ERROR", JOptionPane.ERROR_MESSAGE);
       }
       if(jTextFieldDniCliente.getText().length() <8) {
           
           if(!Character.isDigit(c)) {
               evt.consume();
               
           }
       }
       
       if(jTextFieldDniCliente.getText().length() == 8) {
           if(Character.isDigit(c) || !Character.isLetter(c)) {
               evt.consume();
           }
           
       }
           
    }//GEN-LAST:event_jTextFieldDniClienteKeyTyped

    private void jTextFieldDniClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDniClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDniClienteActionPerformed

    private void jTextFieldDniClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDniClienteKeyPressed
 char c = evt.getKeyChar();
        
        if(jTextFieldDniCliente.getText().length() <8) {
           
           if(!Character.isDigit(c) && evt.getKeyCode() != KeyEvent.VK_BACK_SPACE && evt.getKeyCode() != KeyEvent.VK_CAPS_LOCK) {
               evt.consume();
               JOptionPane.showMessageDialog(this, "Solo se pueden introducir caracteres numericos", "ERROR", JOptionPane.ERROR_MESSAGE);
           }
       }
        if(jTextFieldDniCliente.getText().length() == 8) {
            
            if(Character.isDigit(c) || !Character.isLetter(c) && evt.getKeyCode() != KeyEvent.VK_BACK_SPACE && evt.getKeyCode() != KeyEvent.VK_CAPS_LOCK) {
               evt.consume();
               JOptionPane.showMessageDialog(this, "Debes escribir una letra", "ERROR", JOptionPane.ERROR_MESSAGE);
           }
        }
    }//GEN-LAST:event_jTextFieldDniClienteKeyPressed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        controlador.checkDni();
        controlador.comprobador();
        controlador.limpiaDatos();
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jTextFieldTelefonoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoClienteKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
            
        }
        if(jTextFieldTelefonoCliente.getText().length()>8){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo puede contener 9 digitos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTextFieldTelefonoClienteKeyTyped

    private void jTextFieldTelefonoClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoClienteKeyPressed
 char c = evt.getKeyChar();
        if(!Character.isDigit(c) && evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            JOptionPane.showMessageDialog(this, "Solo se pueden introducir numeros", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTextFieldTelefonoClienteKeyPressed

    private void jTextFieldTelefonoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoClienteActionPerformed

    /**
     *Obtiene el texto del cuadro en el que se escriben los apellidos
     * @return apellidosCliente
     */
    public JTextField getjTextFieldApellidosCliente() {
        return jTextFieldApellidosCliente;
    }

    /**
     *Modifica el valor del cuadro en el que se escriben los apellidos
     * @param jTextFieldApellidosCliente
     */
    public void setjTextFieldApellidosCliente(JTextField jTextFieldApellidosCliente) {
        this.jTextFieldApellidosCliente = jTextFieldApellidosCliente;
    }

    /**
     *Obtiene el texto del cuadro en el que se escriben la direccion
     * @return direccionCliente
     */
    public JTextField getjTextFieldDireccionCliente() {
        return jTextFieldDireccionCliente;
    }

    /**
     *Modifica el valor del cuadro en el que se escribe la direccion
     * @param jTextFieldDireccionCliente
     */
    public void setjTextFieldDireccionCliente(JTextField jTextFieldDireccionCliente) {
        this.jTextFieldDireccionCliente = jTextFieldDireccionCliente;
    }

    /**
     *Obtiene el texto del cuadro en el que se escriben el dni
     * @return dniCliente
     */
    public JTextField getjTextFieldDniCliente() {
        return jTextFieldDniCliente;
    }

    /**
     *Modifica el valor del cuadro en el que se escribe el dni
     * @param jTextFieldDniCliente
     */
    public void setjTextFieldDniCliente(JTextField jTextFieldDniCliente) {
        this.jTextFieldDniCliente = jTextFieldDniCliente;
    }

    /**
     *Obtiene el texto del cuadro en el que se escribe el email
     * @return emailCliente
     */
    public JTextField getjTextFieldEmailCliente() {
        return jTextFieldEmailCliente;
    }

    /**
     *Modifica el valor del cuadro en el que se escribe el email
     * @param jTextFieldEmailCliente
     */
    public void setjTextFieldEmailCliente(JTextField jTextFieldEmailCliente) {
        this.jTextFieldEmailCliente = jTextFieldEmailCliente;
    }

    /**
     *Obtiene el texto del cuadro en el que se escribe el nombre
     * @return nombreCliente
     */
    public JTextField getjTextFieldNombreCliente() {
        return jTextFieldNombreCliente;
    }

    /**
     *Modifica el valor del cuadro en el que se escribe el nombre
     * @param jTextFieldNombreCliente
     */
    public void setjTextFieldNombreCliente(JTextField jTextFieldNombreCliente) {
        this.jTextFieldNombreCliente = jTextFieldNombreCliente;
    }

    /**
     *Obtiene el texto del cuadro en el que se escribe el telefono
     * @return telefonoCliente
     */
    public JTextField getjTextFieldTelefonoCliente() {
        return jTextFieldTelefonoCliente;
    }

    /**
     *Modifica el valor del cuadro en el que se escribe el telefono
     * @param jTextFieldTelefonoCliente
     */
    public void setjTextFieldTelefonoCliente(JTextField jTextFieldTelefonoCliente) {
        this.jTextFieldTelefonoCliente = jTextFieldTelefonoCliente;
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDAnadirCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDAnadirCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDAnadirCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDAnadirCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDAnadirCliente dialog = new JDAnadirCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextFieldApellidosCliente;
    private javax.swing.JTextField jTextFieldDireccionCliente;
    private javax.swing.JTextField jTextFieldDniCliente;
    private javax.swing.JTextField jTextFieldEmailCliente;
    private javax.swing.JTextField jTextFieldNombreCliente;
    private javax.swing.JTextField jTextFieldTelefonoCliente;
    // End of variables declaration//GEN-END:variables
}
