/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import Controlador.ControladorJDAnadirHorario;
import java.awt.event.KeyEvent;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Joaquin
 */
public class JDAnadirHorario extends javax.swing.JDialog {

    private ControladorJDAnadirHorario controlador;

    /**
     * Creates new form JDHorario
     *
     * @param parent
     * @param modal
     */
    public JDAnadirHorario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooserFecha = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonAnadir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSpinnerHoraInicio = new javax.swing.JSpinner();
        jSpinnerMinsInicio = new javax.swing.JSpinner();
        jSpinnerSecInicio = new javax.swing.JSpinner();
        jSpinnerHoraFin = new javax.swing.JSpinner();
        jSpinnerMinFin = new javax.swing.JSpinner();
        jSpinnerSecFin = new javax.swing.JSpinner();
        jComboBoxUsuario = new javax.swing.JComboBox<String>();
        jDateChooserFechaFinal = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jButtonVolver = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir Horario");
        setResizable(false);

        jLabel1.setText("Fecha Inicio:");

        jTextFieldDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescripcionActionPerformed(evt);
            }
        });
        jTextFieldDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDescripcionKeyTyped(evt);
            }
        });

        jLabel3.setText("Descripcion:");

        jLabel4.setText("Nombre del Usuario:");

        jButtonAnadir.setText("Añadir");
        jButtonAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirActionPerformed(evt);
            }
        });

        jLabel5.setText("Hora de inicio:");

        jLabel6.setText("Hora de finalizacion:");

        jSpinnerHoraInicio.setModel(new javax.swing.SpinnerNumberModel(1, 1, 24, 1));

        jSpinnerMinsInicio.setModel(new javax.swing.SpinnerNumberModel(1, 0, 60, 1));

        jSpinnerSecInicio.setModel(new javax.swing.SpinnerNumberModel(1, 0, 60, 1));

        jSpinnerHoraFin.setModel(new javax.swing.SpinnerNumberModel(1, 1, 24, 1));

        jSpinnerMinFin.setModel(new javax.swing.SpinnerNumberModel(1, 0, 60, 1));

        jSpinnerSecFin.setModel(new javax.swing.SpinnerNumberModel(1, 0, 60, 1));

        jComboBoxUsuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Fecha de finalizacion:");

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Añadir Horario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAnadir))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooserFechaFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5))
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jSpinnerHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jSpinnerMinsInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jSpinnerSecInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jDateChooserFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jSpinnerHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jSpinnerMinFin, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jSpinnerSecFin, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(51, 51, 51))
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jDateChooserFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jSpinnerMinsInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerSecInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jDateChooserFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jSpinnerHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerMinFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerSecFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnadir)
                    .addComponent(jButtonVolver))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Devuelve el JComboBoxUsuario
     *
     * @return
     */
    public JComboBox<String> getjComboBoxUsuario() {
        return jComboBoxUsuario;
    }

    /**
     * Devuelve el JComboBoxUsuario
     *
     * @param jComboBoxUsuario
     */

    public void setjComboBoxUsuario(JComboBox<String> jComboBoxUsuario) {
        this.jComboBoxUsuario = jComboBoxUsuario;
    }

    /**
     * Devuelve el JDateChooseFecha
     *
     * @return
     */
    public JDateChooser getjDateChooserFecha() {
        return jDateChooserFecha;
    }

    /**
     * Establece el JDateChooserFecha
     *
     * @param jDateChooserFecha
     */

    public void setjDateChooserFecha(JDateChooser jDateChooserFecha) {
        this.jDateChooserFecha = jDateChooserFecha;
    }

    /**
     * Devuelve el JDateChooserFechaFinal
     *
     * @return
     */

    public JDateChooser getjDateChooserFechaFinal() {
        return jDateChooserFechaFinal;
    }

    /**
     * Establece el JDateChooserFechaFinal
     *
     * @param jDateChooserFechaFinal
     */
    public void setjDateChooserFechaFinal(JDateChooser jDateChooserFechaFinal) {
        this.jDateChooserFechaFinal = jDateChooserFechaFinal;
    }

    /**
     * Devuelve el JSpinnerHoraFin
     *
     * @return
     */

    public JSpinner getjSpinnerHoraFin() {
        return jSpinnerHoraFin;
    }

    /**
     * Establece SpinnerHoraFin
     *
     * @param jSpinnerHoraFin
     */

    public void setjSpinnerHoraFin(JSpinner jSpinnerHoraFin) {
        this.jSpinnerHoraFin = jSpinnerHoraFin;
    }

    /**
     * Devuelve jSpinnerHoraInicio
     *
     * @return
     */
    public JSpinner getjSpinnerHoraInicio() {
        return jSpinnerHoraInicio;
    }

    /**
     * Establece el jSpinnerHoraInicio
     *
     * @param jSpinnerHoraInicio
     */
    public void setjSpinnerHoraInicio(JSpinner jSpinnerHoraInicio) {
        this.jSpinnerHoraInicio = jSpinnerHoraInicio;
    }

    /**
     * Devuelve el jSpinnerMinFin
     *
     * @return
     */

    public JSpinner getjSpinnerMinFin() {
        return jSpinnerMinFin;
    }

    /**
     * Establece el jSpinnerMinFin
     *
     * @param jSpinnerMinFin
     */

    public void setjSpinnerMinFin(JSpinner jSpinnerMinFin) {
        this.jSpinnerMinFin = jSpinnerMinFin;
    }

    /**
     * Devuelve el jSpinnerMinsInicio
     *
     * @return
     */
    public JSpinner getjSpinnerMinsInicio() {
        return jSpinnerMinsInicio;
    }

    /**
     * Establece jSpinnerMinsInicio
     *
     * @param jSpinnerMinsInicio
     */
    public void setjSpinnerMinsInicio(JSpinner jSpinnerMinsInicio) {
        this.jSpinnerMinsInicio = jSpinnerMinsInicio;
    }

    /**
     * Devuelve el jSpinnerSecFin
     *
     * @return
     */

    public JSpinner getjSpinnerSecFin() {
        return jSpinnerSecFin;
    }

    /**
     * Esteblece jSpinnerSecFin
     *
     * @param jSpinnerSecFin
     */

    public void setjSpinnerSecFin(JSpinner jSpinnerSecFin) {
        this.jSpinnerSecFin = jSpinnerSecFin;
    }

    /**
     * Devuelve el jSpinnerSecInicio
     *
     * @return
     */

    public JSpinner getjSpinnerSecInicio() {
        return jSpinnerSecInicio;
    }

    /**
     * Establece jSpinnerSecInicio
     *
     * @param jSpinnerSecInicio
     */

    public void setjSpinnerSecInicio(JSpinner jSpinnerSecInicio) {
        this.jSpinnerSecInicio = jSpinnerSecInicio;
    }

    /**
     * Devuelve el jTextFieldDescripcion
     *
     * @return
     */

    public JTextField getjTextFieldDescripcion() {
        return jTextFieldDescripcion;
    }

    /**
     * Establece jTextFieldDescripcion
     *
     * @param jTextFieldDescripcion
     */

    public void setjTextFieldDescripcion(JTextField jTextFieldDescripcion) {
        this.jTextFieldDescripcion = jTextFieldDescripcion;
    }

    /**
     * Establece el controlador para la vista
     *
     * @param controlador
     */

    public void setControlador(ControladorJDAnadirHorario controlador) {
        this.controlador = controlador;
    }

    /**
     *
     * @param evt
     */
    private void jTextFieldDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescripcionActionPerformed

    private void jButtonAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirActionPerformed
        // TODO add your handling code here:
        controlador.anadirHorario();
    }//GEN-LAST:event_jButtonAnadirActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // TODO add your handling code here:
        controlador.volver();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jTextFieldDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDescripcionKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isLetter(c) && !Character.isDigit(c) && evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {

            evt.consume();
            JOptionPane.showMessageDialog(this, "Debes introducir letras", "ERROR", JOptionPane.ERROR_MESSAGE);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescripcionKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDAnadirHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDAnadirHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDAnadirHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDAnadirHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDAnadirHorario dialog = new JDAnadirHorario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnadir;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxUsuario;
    private com.toedter.calendar.JDateChooser jDateChooserFecha;
    private com.toedter.calendar.JDateChooser jDateChooserFechaFinal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSpinner jSpinnerHoraFin;
    private javax.swing.JSpinner jSpinnerHoraInicio;
    private javax.swing.JSpinner jSpinnerMinFin;
    private javax.swing.JSpinner jSpinnerMinsInicio;
    private javax.swing.JSpinner jSpinnerSecFin;
    private javax.swing.JSpinner jSpinnerSecInicio;
    private javax.swing.JTextField jTextFieldDescripcion;
    // End of variables declaration//GEN-END:variables
}
