/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorJDAnadirUsuario;
import javax.swing.JCheckBox;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Mario
 */
public class JDAnadirUsuario extends javax.swing.JDialog {

    private ControladorJDAnadirUsuario controlador;

    /**
     * Creates new form JDAnadirUsuario
     *
     * @param parent
     * @param modal
     */
    public JDAnadirUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controlador = new ControladorJDAnadirUsuario(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNombre = new javax.swing.JTextField();
        jCheckBoxCliente = new javax.swing.JCheckBox();
        jCheckBoxAdmin = new javax.swing.JCheckBox();
        jCheckBoxProductos = new javax.swing.JCheckBox();
        jCheckBoxProveedores = new javax.swing.JCheckBox();
        jCheckBoxUsuarios = new javax.swing.JCheckBox();
        jButtonAgregar = new javax.swing.JButton();
        jButtonLimpiaDatos = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jPasswordFieldContrasena = new javax.swing.JPasswordField();
        jPasswordFieldContrasena2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir Usuario");

        jTextFieldNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre de Usuario"));

        jCheckBoxCliente.setText("VistaCliente");

        jCheckBoxAdmin.setText("Administrador");

        jCheckBoxProductos.setText("VistaProductos");

        jCheckBoxProveedores.setText("VistaProveedores");

        jCheckBoxUsuarios.setText("VistaUsuarios");

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jButtonLimpiaDatos.setText("Limpiar Datos");
        jButtonLimpiaDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiaDatosActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jPasswordFieldContrasena.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraseña"));

        jPasswordFieldContrasena2.setBorder(javax.swing.BorderFactory.createTitledBorder("Confirmar Contraseña"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNombre)
                    .addComponent(jPasswordFieldContrasena)
                    .addComponent(jPasswordFieldContrasena2, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxCliente)
                    .addComponent(jCheckBoxAdmin)
                    .addComponent(jCheckBoxProductos)
                    .addComponent(jCheckBoxProveedores)
                    .addComponent(jCheckBoxUsuarios))
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAgregar)
                .addGap(51, 51, 51)
                .addComponent(jButtonLimpiaDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButtonCancelar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBoxAdmin)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBoxProductos)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxProveedores))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jPasswordFieldContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxUsuarios)
                    .addComponent(jPasswordFieldContrasena2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAgregar)
                    .addComponent(jButtonLimpiaDatos)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        // TODO add your handling code here:   
        controlador.comprobador();
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonLimpiaDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiaDatosActionPerformed
        // TODO add your handling code here:
        controlador.limpiaDatos();
    }//GEN-LAST:event_jButtonLimpiaDatosActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     *
     * @return
     */
    public JCheckBox getjCheckBoxAdmin() {
        return jCheckBoxAdmin;
    }

    /**
     *
     * @param jCheckBoxAdmin
     */
    public void setjCheckBoxAdmin(JCheckBox jCheckBoxAdmin) {
        this.jCheckBoxAdmin = jCheckBoxAdmin;
    }

    /**
     *
     * @return
     */
    public JCheckBox getjCheckBoxCliente() {
        return jCheckBoxCliente;
    }

    /**
     *
     * @param jCheckBoxCliente
     */
    public void setjCheckBoxCliente(JCheckBox jCheckBoxCliente) {
        this.jCheckBoxCliente = jCheckBoxCliente;
    }

    /**
     *
     * @return
     */
    public JCheckBox getjCheckBoxProductos() {
        return jCheckBoxProductos;
    }

    /**
     *
     * @param jCheckBoxProductos
     */
    public void setjCheckBoxProductos(JCheckBox jCheckBoxProductos) {
        this.jCheckBoxProductos = jCheckBoxProductos;
    }

    /**
     *
     * @return
     */
    public JCheckBox getjCheckBoxProveedores() {
        return jCheckBoxProveedores;
    }

    /**
     *
     * @param jCheckBoxProveedores
     */
    public void setjCheckBoxProveedores(JCheckBox jCheckBoxProveedores) {
        this.jCheckBoxProveedores = jCheckBoxProveedores;
    }

    /**
     *
     * @return
     */
    public JCheckBox getjCheckBoxUsuarios() {
        return jCheckBoxUsuarios;
    }

    /**
     *
     * @param jCheckBoxUsuarios
     */
    public void setjCheckBoxUsuarios(JCheckBox jCheckBoxUsuarios) {
        this.jCheckBoxUsuarios = jCheckBoxUsuarios;
    }

    /**
     *
     * @return
     */
    public JPasswordField getjPasswordFieldContrasena() {
        return jPasswordFieldContrasena;
    }

    /**
     *
     * @param jPasswordFieldContrasena
     */
    public void setjPasswordFieldContrasena(JPasswordField jPasswordFieldContrasena) {
        this.jPasswordFieldContrasena = jPasswordFieldContrasena;
    }

    /**
     *
     * @return
     */
    public JPasswordField getjPasswordFieldContrasena2() {
        return jPasswordFieldContrasena2;
    }

    /**
     *
     * @param jPasswordFieldContrasena2
     */
    public void setjPasswordFieldContrasena2(JPasswordField jPasswordFieldContrasena2) {
        this.jPasswordFieldContrasena2 = jPasswordFieldContrasena2;
    }

    /**
     *
     * @return
     */
    public JTextField getjTextFieldNombre() {
        return jTextFieldNombre;
    }

    /**
     *
     * @param jTextFieldNombre
     */
    public void setjTextFieldNombre(JTextField jTextFieldNombre) {
        this.jTextFieldNombre = jTextFieldNombre;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDAnadirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDAnadirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDAnadirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDAnadirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDAnadirUsuario dialog = new JDAnadirUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonLimpiaDatos;
    private javax.swing.JCheckBox jCheckBoxAdmin;
    private javax.swing.JCheckBox jCheckBoxCliente;
    private javax.swing.JCheckBox jCheckBoxProductos;
    private javax.swing.JCheckBox jCheckBoxProveedores;
    private javax.swing.JCheckBox jCheckBoxUsuarios;
    private javax.swing.JPasswordField jPasswordFieldContrasena;
    private javax.swing.JPasswordField jPasswordFieldContrasena2;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
