/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorJDAnadirUsuario;
import javax.swing.JCheckBox;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Mario
 */
public class JDAnadirUsuario extends javax.swing.JDialog {

    private ControladorJDAnadirUsuario controlador;

    /**
     * Creates new form JDAnadirUsuario
     *
     * @param parent
     * @param modal
     */
    public JDAnadirUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNombre = new javax.swing.JTextField();
        jButtonAgregar = new javax.swing.JButton();
        jButtonLimpiaDatos = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jPasswordFieldContrasena = new javax.swing.JPasswordField();
        jPasswordFieldContrasena2 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jCheckBoxCliente = new javax.swing.JCheckBox();
        jCheckBoxAdmin = new javax.swing.JCheckBox();
        jCheckBoxProductos = new javax.swing.JCheckBox();
        jCheckBoxProveedores = new javax.swing.JCheckBox();
        jCheckBoxUsuarios = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir Usuario");
        setResizable(false);

        jTextFieldNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre de Usuario", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jButtonLimpiaDatos.setText("Limpiar Datos");
        jButtonLimpiaDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiaDatosActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jPasswordFieldContrasena.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contraseña", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        jPasswordFieldContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldContrasenaActionPerformed(evt);
            }
        });

        jPasswordFieldContrasena2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Confirmar Contraseña", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jCheckBoxCliente.setText("VistaCliente");

        jCheckBoxAdmin.setText("Administrador");

        jCheckBoxProductos.setText("VistaProductos");

        jCheckBoxProveedores.setText("VistaProveedores");

        jCheckBoxUsuarios.setText("VistaUsuarios");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Permisos del Usuario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxProveedores)
                    .addComponent(jCheckBoxCliente)
                    .addComponent(jCheckBoxProductos)
                    .addComponent(jCheckBoxAdmin)
                    .addComponent(jCheckBoxUsuarios))
                .addContainerGap(31, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jCheckBoxAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxProveedores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxUsuarios)
                .addGap(19, 19, 19))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Añadir Usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNombre)
                    .addComponent(jPasswordFieldContrasena)
                    .addComponent(jPasswordFieldContrasena2, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jButtonLimpiaDatos)
                .addGap(76, 76, 76)
                .addComponent(jButtonCancelar)
                .addContainerGap())
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPasswordFieldContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPasswordFieldContrasena2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAgregar)
                    .addComponent(jButtonLimpiaDatos)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        // TODO add your handling code here:   
        controlador.comprobador();
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonLimpiaDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiaDatosActionPerformed
        // TODO add your handling code here:
        controlador.limpiaDatos();
    }//GEN-LAST:event_jButtonLimpiaDatosActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jPasswordFieldContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldContrasenaActionPerformed

    /**
     * Devuelve el JChechBoxAdmin
     *
     * @return
     */
    public JCheckBox getjCheckBoxAdmin() {
        return jCheckBoxAdmin;
    }

    /**
     * Establece jCheckBoxAdmin
     *
     * @param jCheckBoxAdmin
     */
    public void setjCheckBoxAdmin(JCheckBox jCheckBoxAdmin) {
        this.jCheckBoxAdmin = jCheckBoxAdmin;
    }

    /**
     * Devuelve JCheckBoxClinte
     *
     * @return
     */
    public JCheckBox getjCheckBoxCliente() {
        return jCheckBoxCliente;
    }

    /**
     * Establece jCheckBoxCliente
     *
     * @param jCheckBoxCliente
     */
    public void setjCheckBoxCliente(JCheckBox jCheckBoxCliente) {
        this.jCheckBoxCliente = jCheckBoxCliente;
    }

    /**
     * Devuelve JCheckBoxProductos
     *
     * @return
     */
    public JCheckBox getjCheckBoxProductos() {
        return jCheckBoxProductos;
    }

    /**
     * Establece JCheckBoxProductos
     *
     * @param jCheckBoxProductos
     */
    public void setjCheckBoxProductos(JCheckBox jCheckBoxProductos) {
        this.jCheckBoxProductos = jCheckBoxProductos;
    }

    /**
     * Devuelve el JCheckBoxProveedore
     *
     * @return
     */
    public JCheckBox getjCheckBoxProveedores() {
        return jCheckBoxProveedores;
    }

    /**
     * Establece el JCheckBoxProveedores
     *
     * @param jCheckBoxProveedores
     */
    public void setjCheckBoxProveedores(JCheckBox jCheckBoxProveedores) {
        this.jCheckBoxProveedores = jCheckBoxProveedores;
    }

    /**
     * Devuelve el JCheckBoxUsuarios
     *
     * @return
     */
    public JCheckBox getjCheckBoxUsuarios() {
        return jCheckBoxUsuarios;
    }

    /**
     * Establece JCheckBoxUsuarios
     *
     * @param jCheckBoxUsuarios
     */
    public void setjCheckBoxUsuarios(JCheckBox jCheckBoxUsuarios) {
        this.jCheckBoxUsuarios = jCheckBoxUsuarios;
    }

    /**
     * Devuelve JPasswordFieldContrasena
     *
     * @return
     */
    public JPasswordField getjPasswordFieldContrasena() {
        return jPasswordFieldContrasena;
    }

    /**
     * Establece jPasswordFieldContrasena
     *
     * @param jPasswordFieldContrasena
     */
    public void setjPasswordFieldContrasena(JPasswordField jPasswordFieldContrasena) {
        this.jPasswordFieldContrasena = jPasswordFieldContrasena;
    }

    /**
     * Devuelve jPasswordContrasena2
     *
     * @return
     */
    public JPasswordField getjPasswordFieldContrasena2() {
        return jPasswordFieldContrasena2;
    }

    /**
     * Establece JPasswordFieldContrasena2
     *
     * @param jPasswordFieldContrasena2
     */
    public void setjPasswordFieldContrasena2(JPasswordField jPasswordFieldContrasena2) {
        this.jPasswordFieldContrasena2 = jPasswordFieldContrasena2;
    }

    /**
     * Devuelve JTextFieldNombre
     *
     * @return
     */
    public JTextField getjTextFieldNombre() {
        return jTextFieldNombre;
    }

    /**
     * Establece jTextFieldNombre
     *
     * @param jTextFieldNombre
     */
    public void setjTextFieldNombre(JTextField jTextFieldNombre) {
        this.jTextFieldNombre = jTextFieldNombre;
    }

    /**
     * Establece el controlador para la vista
     *
     * @param controlador
     */
    public void setControlador(ControladorJDAnadirUsuario controlador) {
        this.controlador = controlador;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDAnadirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDAnadirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDAnadirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDAnadirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDAnadirUsuario dialog = new JDAnadirUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonLimpiaDatos;
    private javax.swing.JCheckBox jCheckBoxAdmin;
    private javax.swing.JCheckBox jCheckBoxCliente;
    private javax.swing.JCheckBox jCheckBoxProductos;
    private javax.swing.JCheckBox jCheckBoxProveedores;
    private javax.swing.JCheckBox jCheckBoxUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldContrasena;
    private javax.swing.JPasswordField jPasswordFieldContrasena2;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
