/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorJDTablaArticulos;
import Controlador.ControladorJDTablaClientes;
import Controlador.ControladorJDTablaUsuarios;
import Controlador.ControladorJDTablaProveedor;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Mario
 */
public class JDTablaUsuariosClientesProveedorArticulo extends javax.swing.JDialog {

    private ControladorJDTablaUsuarios controladorUsuario;
    private ControladorJDTablaClientes controladorClientes;
    private ControladorJDTablaProveedor controladorProveedor;
    private ControladorJDTablaArticulos controladorArticulo;
    private int ventana;
    private TableRowSorter trsfiltro;

    /**
     * Creates new form JDTablaUsuariosClientes
     *
     * @param parent
     * @param modal
     */
    public JDTablaUsuariosClientesProveedorArticulo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     *
     * Constructor parametrizado
     *
     * @param botones
     * @param ventana
     */
    public JDTablaUsuariosClientesProveedorArticulo(int botones, int ventana) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.ventana = ventana;

        if (botones == 0) {
            jButtonBorrar.setVisible(false);
            jButtonGuardar.setVisible(false);
            jButtonVolver.setVisible(true);
        } else if (botones == 1) {
            jButtonBorrar.setVisible(true);
            jButtonGuardar.setVisible(false);
            jButtonVolver.setVisible(true);
        } else if (botones == 2) {
            jButtonBorrar.setVisible(false);
            jButtonGuardar.setVisible(true);
            jButtonVolver.setVisible(true);
        }

    }

    /**
     * Metodo para filtrar el contenido de la tabla
     */
    public void filtro() {
        trsfiltro.setRowFilter(RowFilter.regexFilter(jTextFieldFiltrado.getText(), 0));
    }

    /**
     * Obtiene el tableModel de la clase TableUsuariosClientes
     *
     * @return tableModel
     */
    public JTable getjTableUsuariosClientes() {
        return jTableUsuariosClientes;
    }

    /**
     * Modifica y selecciona el modelo
     *
     * @param tm
     */
    public void setjTableUsuariosClientes(TableModel tm) {
        this.jTableUsuariosClientes.setModel(tm);
    }

    /**
     * Obtiene el texto filtrado
     *
     * @return textoFiltrado
     */
    public JTextField getjTextFieldFiltrado() {
        return jTextFieldFiltrado;
    }

    /**
     * Modifica el texto filtrado
     *
     * @param jTextFieldFiltrado
     */
    public void setjTextFieldFiltrado(JTextField jTextFieldFiltrado) {
        this.jTextFieldFiltrado = jTextFieldFiltrado;
    }

    /**
     * Establece el controlador para la vista con usuario
     *
     * @param controladorUsuario
     */
    public void setControladorUsuario(ControladorJDTablaUsuarios controladorUsuario) {
        this.controladorUsuario = controladorUsuario;
    }

    /**
     * Establece el controlador para la vista con clientes
     *
     * @param controladorClientes
     */
    public void setControladorClientes(ControladorJDTablaClientes controladorClientes) {
        this.controladorClientes = controladorClientes;
    }

    /**
     * Establece el controlador para la vista proveedor
     *
     * @param controladorProveedor
     */
    public void setControladorProveedor(ControladorJDTablaProveedor controladorProveedor) {
        this.controladorProveedor = controladorProveedor;
    }

    /**
     * Establece el controlador para la vista articulo
     *
     * @param controladorArticulo
     */
    public void setControladorArticulo(ControladorJDTablaArticulos controladorArticulo) {
        this.controladorArticulo = controladorArticulo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuariosClientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldFiltrado = new javax.swing.JTextField();
        jButtonBorrar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTableUsuariosClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableUsuariosClientes);

        jLabel1.setText("Filtrar(Case Sensitive):");

        jTextFieldFiltrado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldFiltradoKeyTyped(evt);
            }
        });

        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButtonBorrar)
                .addGap(208, 208, 208)
                .addComponent(jButtonVolver)
                .addGap(224, 224, 224)
                .addComponent(jButtonGuardar)
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldFiltrado, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldFiltrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBorrar)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonVolver))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldFiltradoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFiltradoKeyTyped
        // TODO add your handling code here:
        jTextFieldFiltrado.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                filtro();
            }
        });
        trsfiltro = new TableRowSorter(jTableUsuariosClientes.getModel());
        jTableUsuariosClientes.setRowSorter(trsfiltro);
    }//GEN-LAST:event_jTextFieldFiltradoKeyTyped

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        // TODO add your handling code here:
        if (ventana == 0) {
            controladorUsuario.eliminaUsuario();
        } else if (ventana == 1) {
            controladorClientes.eliminaCliente();
        } else if (ventana == 2) {
            controladorProveedor.eliminaProveedor();
        } else if (ventana == 3) {
            controladorArticulo.eliminaArticulo();
        }
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        if (ventana == 0) {
            controladorUsuario.modificaUsuario();

        } else if (ventana == 1) {
            controladorClientes.modificaCliente();
        } else if (ventana == 2) {
            controladorProveedor.modificaProveedor();
        } else if (ventana == 3) {
            controladorArticulo.modificaArticulo();
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDTablaUsuariosClientesProveedorArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDTablaUsuariosClientesProveedorArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDTablaUsuariosClientesProveedorArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDTablaUsuariosClientesProveedorArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDTablaUsuariosClientesProveedorArticulo dialog = new JDTablaUsuariosClientesProveedorArticulo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsuariosClientes;
    private javax.swing.JTextField jTextFieldFiltrado;
    // End of variables declaration//GEN-END:variables
}
