/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorJFGestionUsuarios;

/**
 *
 * @author Mario
 */
public class JFGestionUsuarios extends javax.swing.JFrame {

    private ControladorJFGestionUsuarios controlador;
    /**
     * Creates new form JFGestionUsuarios
     */
    public JFGestionUsuarios() {
        initComponents();
        controlador = new ControladorJFGestionUsuarios(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAnadirUsuario = new javax.swing.JButton();
        jButtonBorraUsuario = new javax.swing.JButton();
        jButtonModificaUsuario = new javax.swing.JButton();
        jButtonVerUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú de Gestión de Usuarios");

        jButtonAnadirUsuario.setText("Añadir Usuario");
        jButtonAnadirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirUsuarioActionPerformed(evt);
            }
        });

        jButtonBorraUsuario.setText("Borrar Usuario");
        jButtonBorraUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorraUsuarioActionPerformed(evt);
            }
        });

        jButtonModificaUsuario.setText("Modificar Usuario");
        jButtonModificaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificaUsuarioActionPerformed(evt);
            }
        });

        jButtonVerUsuario.setText("Ver Usuarios");
        jButtonVerUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonVerUsuario)
                    .addComponent(jButtonModificaUsuario)
                    .addComponent(jButtonBorraUsuario)
                    .addComponent(jButtonAnadirUsuario))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jButtonAnadirUsuario)
                .addGap(32, 32, 32)
                .addComponent(jButtonBorraUsuario)
                .addGap(32, 32, 32)
                .addComponent(jButtonModificaUsuario)
                .addGap(40, 40, 40)
                .addComponent(jButtonVerUsuario)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnadirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirUsuarioActionPerformed
        // TODO add your handling code here:
        controlador.anadirUsuario();
    }//GEN-LAST:event_jButtonAnadirUsuarioActionPerformed

    private void jButtonBorraUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorraUsuarioActionPerformed
        // TODO add your handling code here:
        controlador.borrarUsuarios();
    }//GEN-LAST:event_jButtonBorraUsuarioActionPerformed

    private void jButtonModificaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificaUsuarioActionPerformed
        // TODO add your handling code here:
        controlador.modificarUsuarios();
    }//GEN-LAST:event_jButtonModificaUsuarioActionPerformed

    private void jButtonVerUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerUsuarioActionPerformed
        // TODO add your handling code here:
        controlador.verUsuarios();
    }//GEN-LAST:event_jButtonVerUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFGestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFGestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFGestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFGestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFGestionUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnadirUsuario;
    private javax.swing.JButton jButtonBorraUsuario;
    private javax.swing.JButton jButtonModificaUsuario;
    private javax.swing.JButton jButtonVerUsuario;
    // End of variables declaration//GEN-END:variables
}
